# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

pool:
  vmImage: 'Ubuntu-16.04'

container: 
    image: humandoodlebug/pandoc

steps:
- script: make -C report
  displayName: 'Compile report'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: 'report/report.pdf'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'
  displayName: 'Publish Build Artifacts'
